
package usr.speedy.ds.client.overview;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OverviewService", targetNamespace = "http://overview.ds.speedy.usr/", wsdlLocation = "http://localhost:8083/DS3/overview?wsdl")
public class OverviewService
    extends Service
{

    private final static URL OVERVIEWSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(usr.speedy.ds.client.overview.OverviewService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = usr.speedy.ds.client.overview.OverviewService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8083/DS3/overview?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8083/DS3/overview?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        OVERVIEWSERVICE_WSDL_LOCATION = url;
    }

    public OverviewService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OverviewService() {
        super(OVERVIEWSERVICE_WSDL_LOCATION, new QName("http://overview.ds.speedy.usr/", "OverviewService"));
    }

    /**
     * 
     * @return
     *     returns Overview
     */
    @WebEndpoint(name = "OverviewPort")
    public Overview getOverviewPort() {
        return super.getPort(new QName("http://overview.ds.speedy.usr/", "OverviewPort"), Overview.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Overview
     */
    @WebEndpoint(name = "OverviewPort")
    public Overview getOverviewPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://overview.ds.speedy.usr/", "OverviewPort"), Overview.class, features);
    }

}
