
package usr.speedy.ds.client.tasks;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FoundTaskService", targetNamespace = "http://ds.speedy.usr/", wsdlLocation = "http://localhost:8083/DS3/modify?wsdl")
public class FoundTaskService
    extends Service
{

    private final static URL FOUNDTASKSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8083/DS3/modify?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        FOUNDTASKSERVICE_WSDL_LOCATION = url;
    }

    public FoundTaskService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FoundTaskService() {
        super(FOUNDTASKSERVICE_WSDL_LOCATION, new QName("http://ds.speedy.usr/", "FoundTaskService"));
    }

    /**
     * 
     * @return
     *     returns FoundTask
     */
    @WebEndpoint(name = "FoundTaskPort")
    public FoundTask getFoundTaskPort() {
        return (FoundTask)super.getPort(new QName("http://ds.speedy.usr/", "FoundTaskPort"), FoundTask.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FoundTask
     */
    @WebEndpoint(name = "FoundTaskPort")
    public FoundTask getFoundTaskPort(WebServiceFeature... features) {
        return (FoundTask)super.getPort(new QName("http://ds.speedy.usr/", "FoundTaskPort"), FoundTask.class, features);
    }

}
