
package usr.speedy.ds.client.tasks;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FoundTask", targetNamespace = "http://ds.speedy.usr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FoundTask {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "foundTask", targetNamespace = "http://ds.speedy.usr/", className = "usr.speedy.ds.client.tasks.FoundTask_Type")
    @ResponseWrapper(localName = "foundTaskResponse", targetNamespace = "http://ds.speedy.usr/", className = "usr.speedy.ds.client.tasks.FoundTaskResponse")
    public String foundTask(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
