
package usr.speedy.ds.client.overview;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Overview", targetNamespace = "http://overview.ds.speedy.usr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Overview {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTasks", targetNamespace = "http://overview.ds.speedy.usr/", className = "usr.speedy.ds.client.overview.GetTasks")
    @ResponseWrapper(localName = "getTasksResponse", targetNamespace = "http://overview.ds.speedy.usr/", className = "usr.speedy.ds.client.overview.GetTasksResponse")
    public List<String> getTasks();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOpenTasks", targetNamespace = "http://overview.ds.speedy.usr/", className = "usr.speedy.ds.client.overview.GetOpenTasks")
    @ResponseWrapper(localName = "getOpenTasksResponse", targetNamespace = "http://overview.ds.speedy.usr/", className = "usr.speedy.ds.client.overview.GetOpenTasksResponse")
    public List<String> getOpenTasks();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClosedTaks", targetNamespace = "http://overview.ds.speedy.usr/", className = "usr.speedy.ds.client.overview.GetClosedTaks")
    @ResponseWrapper(localName = "getClosedTaksResponse", targetNamespace = "http://overview.ds.speedy.usr/", className = "usr.speedy.ds.client.overview.GetClosedTaksResponse")
    public List<String> getClosedTaks();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAvailableProgrammers", targetNamespace = "http://overview.ds.speedy.usr/", className = "usr.speedy.ds.client.overview.GetAvailableProgrammers")
    @ResponseWrapper(localName = "getAvailableProgrammersResponse", targetNamespace = "http://overview.ds.speedy.usr/", className = "usr.speedy.ds.client.overview.GetAvailableProgrammersResponse")
    public List<String> getAvailableProgrammers();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBusyProgrammers", targetNamespace = "http://overview.ds.speedy.usr/", className = "usr.speedy.ds.client.overview.GetBusyProgrammers")
    @ResponseWrapper(localName = "getBusyProgrammersResponse", targetNamespace = "http://overview.ds.speedy.usr/", className = "usr.speedy.ds.client.overview.GetBusyProgrammersResponse")
    public List<String> getBusyProgrammers();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProgrammersForTask", targetNamespace = "http://overview.ds.speedy.usr/", className = "usr.speedy.ds.client.overview.GetProgrammersForTask")
    @ResponseWrapper(localName = "getProgrammersForTaskResponse", targetNamespace = "http://overview.ds.speedy.usr/", className = "usr.speedy.ds.client.overview.GetProgrammersForTaskResponse")
    public List<String> getProgrammersForTask(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
