
package usr.speedy.ds.client.tasks;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ModifyTaskService", targetNamespace = "http://ds.speedy.usr/", wsdlLocation = "http://localhost:8083/DS3/find?wsdl")
public class ModifyTaskService
    extends Service
{

    private final static URL MODIFYTASKSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8083/DS3/find?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        MODIFYTASKSERVICE_WSDL_LOCATION = url;
    }

    public ModifyTaskService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModifyTaskService() {
        super(MODIFYTASKSERVICE_WSDL_LOCATION, new QName("http://ds.speedy.usr/", "ModifyTaskService"));
    }

    /**
     * 
     * @return
     *     returns ModifyTask
     */
    @WebEndpoint(name = "ModifyTaskPort")
    public ModifyTask getModifyTaskPort() {
        return (ModifyTask)super.getPort(new QName("http://ds.speedy.usr/", "ModifyTaskPort"), ModifyTask.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModifyTask
     */
    @WebEndpoint(name = "ModifyTaskPort")
    public ModifyTask getModifyTaskPort(WebServiceFeature... features) {
        return (ModifyTask)super.getPort(new QName("http://ds.speedy.usr/", "ModifyTaskPort"), ModifyTask.class, features);
    }

}
